/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppLeaderboardsRouteImport } from './routes/_app.leaderboards'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppConnectRouteImport } from './routes/_app.connect'
import { Route as AppSalesIndexRouteImport } from './routes/_app.sales.index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app.expenses.index'
import { Route as AppConnectIndexRouteImport } from './routes/_app.connect.index'
import { Route as AppAgentsIndexRouteImport } from './routes/_app.agents.index'
import { Route as AppSalesNewRouteImport } from './routes/_app.sales.new'
import { Route as AppExpensesNewRouteImport } from './routes/_app.expenses.new'
import { Route as AppConnectCallbackRouteImport } from './routes/_app.connect.callback'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app.agents.$agentId'
import { Route as ApiPublicHooksGhlWebhookRouteImport } from './routes/api/public/hooks/ghl-webhook'
import { Route as ApiPublicHooksGhlRefreshRouteImport } from './routes/api/public/hooks/ghl-refresh'
import { Route as AppSalesSaleIdEditRouteImport } from './routes/_app.sales.$saleId.edit'
import { Route as AppExpensesExpenseIdEditRouteImport } from './routes/_app.expenses.$expenseId.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderboardsRoute = AppLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectIndexRoute = AppConnectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConnectRoute,
} as any)
const AppAgentsIndexRoute = AppAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesNewRoute = AppSalesNewRouteImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesNewRoute = AppExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectCallbackRoute = AppConnectCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AppConnectRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHooksGhlWebhookRoute =
  ApiPublicHooksGhlWebhookRouteImport.update({
    id: '/api/public/hooks/ghl-webhook',
    path: '/api/public/hooks/ghl-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGhlRefreshRoute =
  ApiPublicHooksGhlRefreshRouteImport.update({
    id: '/api/public/hooks/ghl-refresh',
    path: '/api/public/hooks/ghl-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSalesSaleIdEditRoute = AppSalesSaleIdEditRouteImport.update({
  id: '/sales/$saleId/edit',
  path: '/sales/$saleId/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesExpenseIdEditRoute =
  AppExpensesExpenseIdEditRouteImport.update({
    id: '/expenses/$expenseId/edit',
    path: '/expenses/$expenseId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/connect': typeof AppConnectRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/leaderboards': typeof AppLeaderboardsRoute
  '/settings': typeof AppSettingsRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/connect/callback': typeof AppConnectCallbackRoute
  '/expenses/new': typeof AppExpensesNewRoute
  '/sales/new': typeof AppSalesNewRoute
  '/agents/': typeof AppAgentsIndexRoute
  '/connect/': typeof AppConnectIndexRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/sales/': typeof AppSalesIndexRoute
  '/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/sales/$saleId/edit': typeof AppSalesSaleIdEditRoute
  '/api/public/hooks/ghl-refresh': typeof ApiPublicHooksGhlRefreshRoute
  '/api/public/hooks/ghl-webhook': typeof ApiPublicHooksGhlWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/leaderboards': typeof AppLeaderboardsRoute
  '/settings': typeof AppSettingsRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/connect/callback': typeof AppConnectCallbackRoute
  '/expenses/new': typeof AppExpensesNewRoute
  '/sales/new': typeof AppSalesNewRoute
  '/agents': typeof AppAgentsIndexRoute
  '/connect': typeof AppConnectIndexRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/sales': typeof AppSalesIndexRoute
  '/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/sales/$saleId/edit': typeof AppSalesSaleIdEditRoute
  '/api/public/hooks/ghl-refresh': typeof ApiPublicHooksGhlRefreshRoute
  '/api/public/hooks/ghl-webhook': typeof ApiPublicHooksGhlWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/connect': typeof AppConnectRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leaderboards': typeof AppLeaderboardsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/_app/connect/callback': typeof AppConnectCallbackRoute
  '/_app/expenses/new': typeof AppExpensesNewRoute
  '/_app/sales/new': typeof AppSalesNewRoute
  '/_app/agents/': typeof AppAgentsIndexRoute
  '/_app/connect/': typeof AppConnectIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/sales/': typeof AppSalesIndexRoute
  '/_app/expenses/$expenseId/edit': typeof AppExpensesExpenseIdEditRoute
  '/_app/sales/$saleId/edit': typeof AppSalesSaleIdEditRoute
  '/api/public/hooks/ghl-refresh': typeof ApiPublicHooksGhlRefreshRoute
  '/api/public/hooks/ghl-webhook': typeof ApiPublicHooksGhlWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/connect'
    | '/dashboard'
    | '/leaderboards'
    | '/settings'
    | '/agents/$agentId'
    | '/connect/callback'
    | '/expenses/new'
    | '/sales/new'
    | '/agents/'
    | '/connect/'
    | '/expenses/'
    | '/sales/'
    | '/expenses/$expenseId/edit'
    | '/sales/$saleId/edit'
    | '/api/public/hooks/ghl-refresh'
    | '/api/public/hooks/ghl-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/leaderboards'
    | '/settings'
    | '/agents/$agentId'
    | '/connect/callback'
    | '/expenses/new'
    | '/sales/new'
    | '/agents'
    | '/connect'
    | '/expenses'
    | '/sales'
    | '/expenses/$expenseId/edit'
    | '/sales/$saleId/edit'
    | '/api/public/hooks/ghl-refresh'
    | '/api/public/hooks/ghl-webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/connect'
    | '/_app/dashboard'
    | '/_app/leaderboards'
    | '/_app/settings'
    | '/_app/agents/$agentId'
    | '/_app/connect/callback'
    | '/_app/expenses/new'
    | '/_app/sales/new'
    | '/_app/agents/'
    | '/_app/connect/'
    | '/_app/expenses/'
    | '/_app/sales/'
    | '/_app/expenses/$expenseId/edit'
    | '/_app/sales/$saleId/edit'
    | '/api/public/hooks/ghl-refresh'
    | '/api/public/hooks/ghl-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicHooksGhlRefreshRoute: typeof ApiPublicHooksGhlRefreshRoute
  ApiPublicHooksGhlWebhookRoute: typeof ApiPublicHooksGhlWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leaderboards': {
      id: '/_app/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof AppLeaderboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect': {
      id: '/_app/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/': {
      id: '/_app/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect/': {
      id: '/_app/connect/'
      path: '/'
      fullPath: '/connect/'
      preLoaderRoute: typeof AppConnectIndexRouteImport
      parentRoute: typeof AppConnectRoute
    }
    '/_app/agents/': {
      id: '/_app/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AppAgentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales/new': {
      id: '/_app/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof AppSalesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/new': {
      id: '/_app/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof AppExpensesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connect/callback': {
      id: '/_app/connect/callback'
      path: '/callback'
      fullPath: '/connect/callback'
      preLoaderRoute: typeof AppConnectCallbackRouteImport
      parentRoute: typeof AppConnectRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/ghl-webhook': {
      id: '/api/public/hooks/ghl-webhook'
      path: '/api/public/hooks/ghl-webhook'
      fullPath: '/api/public/hooks/ghl-webhook'
      preLoaderRoute: typeof ApiPublicHooksGhlWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ghl-refresh': {
      id: '/api/public/hooks/ghl-refresh'
      path: '/api/public/hooks/ghl-refresh'
      fullPath: '/api/public/hooks/ghl-refresh'
      preLoaderRoute: typeof ApiPublicHooksGhlRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sales/$saleId/edit': {
      id: '/_app/sales/$saleId/edit'
      path: '/sales/$saleId/edit'
      fullPath: '/sales/$saleId/edit'
      preLoaderRoute: typeof AppSalesSaleIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses/$expenseId/edit': {
      id: '/_app/expenses/$expenseId/edit'
      path: '/expenses/$expenseId/edit'
      fullPath: '/expenses/$expenseId/edit'
      preLoaderRoute: typeof AppExpensesExpenseIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppConnectRouteChildren {
  AppConnectCallbackRoute: typeof AppConnectCallbackRoute
  AppConnectIndexRoute: typeof AppConnectIndexRoute
}

const AppConnectRouteChildren: AppConnectRouteChildren = {
  AppConnectCallbackRoute: AppConnectCallbackRoute,
  AppConnectIndexRoute: AppConnectIndexRoute,
}

const AppConnectRouteWithChildren = AppConnectRoute._addFileChildren(
  AppConnectRouteChildren,
)

interface AppRouteChildren {
  AppConnectRoute: typeof AppConnectRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaderboardsRoute: typeof AppLeaderboardsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
  AppExpensesNewRoute: typeof AppExpensesNewRoute
  AppSalesNewRoute: typeof AppSalesNewRoute
  AppAgentsIndexRoute: typeof AppAgentsIndexRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppExpensesExpenseIdEditRoute: typeof AppExpensesExpenseIdEditRoute
  AppSalesSaleIdEditRoute: typeof AppSalesSaleIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectRoute: AppConnectRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaderboardsRoute: AppLeaderboardsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
  AppExpensesNewRoute: AppExpensesNewRoute,
  AppSalesNewRoute: AppSalesNewRoute,
  AppAgentsIndexRoute: AppAgentsIndexRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppExpensesExpenseIdEditRoute: AppExpensesExpenseIdEditRoute,
  AppSalesSaleIdEditRoute: AppSalesSaleIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicHooksGhlRefreshRoute: ApiPublicHooksGhlRefreshRoute,
  ApiPublicHooksGhlWebhookRoute: ApiPublicHooksGhlWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
